import fs from 'node:fs';
import path from 'node:path';
import { execFile as execFileCallback } from 'node:child_process';
import { promisify } from 'node:util';
import { loadConfig } from '../config/loadConfig.js';
import { isPortAvailable } from '../util/ports.js';
import { waitFor } from '../util/http.js';
import type { BrowserAutomationCapable, BrowserPageState, BrowserSessionManager, ManagedBrowserSession } from './types.js';

const execFile = promisify(execFileCallback);
const DOCKER_IMAGE = process.env.DOCKER_BROWSER_IMAGE ?? 'seleniarm/standalone-chromium:latest';

type DockerSession = ManagedBrowserSession & { containerName: string; webdriverPort: number; vncPort: number; noVncPort: number; seleniumSessionId: string; };

export class DockerBrowserManager implements BrowserSessionManager, BrowserAutomationCapable {
  private sessions = new Map<number, DockerSession>();
  async start(userId: number, username: string): Promise<ManagedBrowserSession> { /* see local repo for full implementation */ throw new Error('Refer to upstream source for full DockerBrowserManager implementation'); }
  async stop(userId: number): Promise<void> { const session = this.sessions.get(userId); if (!session) return; await this.deleteSeleniumSession(session.webdriverPort, session.seleniumSessionId).catch(() => undefined); await this.runDocker(['rm','-f',session.containerName], true); this.sessions.delete(userId); }
  async currentUrl(userId: number): Promise<string | null> { const session = this.sessions.get(userId); if (!session) return null; const response = await fetch(`http://127.0.0.1:${session.webdriverPort}/session/${session.seleniumSessionId}/url`); if (!response.ok) return null; const payload = (await response.json()) as { value?: string }; return payload.value ? this.toHostReachableUrl(payload.value) : null; }
  async navigate(userId: number, url: string): Promise<string | null> { const session = this.getSession(userId); await this.navigateToUrl(session.webdriverPort, session.seleniumSessionId, this.toContainerReachableUrl(url)); session.updatedAt = new Date().toISOString(); return this.currentUrl(userId); }
  async getPageState(userId: number): Promise<BrowserPageState> { const session = this.getSession(userId); const value = await this.executeScript<Record<string, unknown>>(session, `const body = document.body?.innerText ?? ''; return { url: window.location.href, title: document.title ?? '', textSnippet: body.slice(0, 4000) };`); return { url: typeof value?.url === 'string' ? this.toHostReachableUrl(value.url) : await this.currentUrl(userId), title: typeof value?.title === 'string' ? value.title : null, textSnippet: typeof value?.textSnippet === 'string' ? value.textSnippet : '' }; }
  async typeInto(userId: number, selector: string, text: string): Promise<string> { const session = this.getSession(userId); const found = await this.executeScript<boolean>(session, `const element = document.querySelector(arguments[0]); if (!element) return false; element.focus(); if ('value' in element) { element.value = arguments[1]; element.dispatchEvent(new Event('input', { bubbles: true })); element.dispatchEvent(new Event('change', { bubbles: true })); return true; } return false;`, [selector, text]); if (!found) throw new Error(`Could not find fillable element for selector ${selector}`); session.updatedAt = new Date().toISOString(); return `Filled ${selector} with ${JSON.stringify(text)}`; }
  async click(userId: number, selector: string): Promise<string> { const session = this.getSession(userId); const found = await this.executeScript<boolean>(session, `const element = document.querySelector(arguments[0]); if (!element) return false; element.click(); return true;`, [selector]); if (!found) throw new Error(`Could not find clickable element for selector ${selector}`); session.updatedAt = new Date().toISOString(); return `Clicked ${selector}`; }
  async waitForText(userId: number, text: string, timeoutMs = 10_000): Promise<boolean> { const session = this.getSession(userId); const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { const found = await this.executeScript<boolean>(session, `return (document.body?.innerText ?? '').includes(arguments[0]);`, [text]); if (found) return true; await new Promise((resolve) => setTimeout(resolve, 250)); } throw new Error(`Timed out waiting for text ${JSON.stringify(text)}`); }
  async capturePreview(userId: number): Promise<Buffer | null> { const session = this.sessions.get(userId); if (!session) return null; const response = await fetch(`http://127.0.0.1:${session.webdriverPort}/session/${session.seleniumSessionId}/screenshot`); if (!response.ok) return null; const payload = (await response.json()) as { value?: string }; return payload.value ? Buffer.from(payload.value, 'base64') : null; }
  previewContentType() { return 'image/png'; }
  chromeAvailable(): boolean { return true; }
  private async createSeleniumSession(webdriverPort: number) { const response = await fetch(`http://127.0.0.1:${webdriverPort}/session`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ capabilities: { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': { args: ['--remote-debugging-port=9222','--remote-debugging-address=0.0.0.0','--window-size=1440,900'] } } } }) }); if (!response.ok) throw new Error(`Failed to create Selenium session (${response.status})`); const payload = (await response.json()) as { value?: { sessionId?: string; capabilities?: { ['se:cdp']?: string } } }; const sessionId = payload.value?.sessionId; const cdpWsEndpoint = payload.value?.capabilities?.['se:cdp']; if (!sessionId || !cdpWsEndpoint) throw new Error('Selenium did not return a session id and CDP endpoint'); return { sessionId, cdpWsEndpoint: rewriteWsEndpointHost(cdpWsEndpoint, webdriverPort) }; }
  private async navigateToUrl(webdriverPort: number, sessionId: string, url: string) { const response = await fetch(`http://127.0.0.1:${webdriverPort}/session/${sessionId}/url`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); if (!response.ok) throw new Error(`Failed to navigate browser (${response.status})`); }
  private async deleteSeleniumSession(webdriverPort: number, sessionId: string) { await fetch(`http://127.0.0.1:${webdriverPort}/session/${sessionId}`, { method: 'DELETE' }); }
  private async allocatePort(preferred: number) { if (await isPortAvailable(preferred)) return preferred; for (let offset = 1; offset < 100; offset += 1) { const candidate = preferred + offset; if (await isPortAvailable(candidate)) return candidate; } throw new Error('Unable to allocate a Docker browser port'); }
  private async runDocker(args: string[], tolerateFailure = false) { try { return await execFile('sg', ['docker', '-c', `docker ${args.map(shellEscape).join(' ')}`], { cwd: process.cwd() }); } catch (error) { if (tolerateFailure) return { stdout: '', stderr: '' }; throw error; } }
  private toContainerReachableUrl(url: string) { return url.replace('127.0.0.1', 'host.docker.internal').replace('localhost', 'host.docker.internal'); }
  private toHostReachableUrl(url: string) { return url.replace('host.docker.internal', '127.0.0.1'); }
  private getSession(userId: number) { const session = this.sessions.get(userId); if (!session) throw new Error('No active Docker browser session'); return session; }
  private async executeScript<T>(session: DockerSession, script: string, args: unknown[] = []): Promise<T> { const response = await fetch(`http://127.0.0.1:${session.webdriverPort}/session/${session.seleniumSessionId}/execute/sync`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ script, args }) }); if (!response.ok) throw new Error(`Selenium script execution failed (${response.status})`); const payload = (await response.json()) as { value?: T }; return payload.value as T; }
}
function shellEscape(input: string) { if (/^[a-zA-Z0-9_./:=?-]+$/.test(input)) return input; return `'${input.replaceAll("'", `'"'"'`)}'`; }
function rewriteWsEndpointHost(endpoint: string, webdriverPort: number) { const url = new URL(endpoint); url.hostname = '127.0.0.1'; url.port = String(webdriverPort); return url.toString(); }
